export const ERROR = {
  ID_INPUT: '이메일을 입력해주세요.',
  ID_EMAIL_VALID: '이메일 형식이 아닙니다.',
  NAME_INPUT: '이름을 입력해주세요.',
  NAME_MIN_LENGTH: '이름은 최소 2글자 입력해주세요.',
  EMAIL_INPUT: '이메일을 입력해주세요.',
  EMAIL_VALID: '이메일 형식이 아닙니다.',
  PASSWORD_INPUT: '비밀번호를 입력해주세요.',
  PASSWORD_MIN_LENGTH: '비밀번호는 최소 8자 입니다.',
  PASSWORD_SAME: '작성된 비밀번호와 일치하지 않습니다.',
  PASSWORD_CURRENT: '정보를 변경하려면, 현재의 비밀번호가 필요합니다.',
  NICKNAME_INPUT: '닉네임을 입력해주세요.',
  NICKNAME_IS_ALEADY: '이미 사용중인 닉네임입니다.',
  NICKNAME_MIN_LENGTH: '이름은 최소 2글자 입력해주세요.',
  PHONE_INPUT: '전화번호를 입력해주세요.',
  PHONE_VALID: '전화번호 형식이 아닙니다.',
  OWNER_REGISTRATION_NUMBER_INPUT: '사업자 등록번호를 입력해주세요.',
  OWNER_REGISTRATION_NUMBER_VALID: '사업자 등록번호 형식이 아닙니다.',
  ADMIN_CODE_INPUT: '관리자 코드를 입력해주세요.',
  ADMIN_CODE_INPUT_VALID: 'ADMIN CODE가 일치하지 않습니다.',
  RESTAURANT_NAME: '업체명을 입력해주세요.',
};
