export const LABELTITLE = {
  ID: '아이디',
  PASSWORD: '비밀번호',
  PASSWORD_CONFIRM: '비밀번호 확인',
  PASSWORD_CURRENT: '현재 비밀번호',
  NAME: '이름',
  NICKNAME: '닉네임',
  EMAIL: '이메일',
  PHONE: '전화번호',
  ROLE_OWNER: '사장님이신가요?',
  ROLE_OWNER_SUB_TITLE: '사업관리자 계정으로 회원가입하기',
  ROLE_ADMIN: '관리자로 가입하기',
  AMDIN_CODE: 'ADMIN CODE',
  OWNER_REGISTRATION_NUMBER: '사업자 등록번호',
  RESTAURANT_NAME: '업체명',
  RESTAURANT_OFFICE: '지점',
  RESTAURANT_PHONE: '대표번호',
  RESTAURANT_CATEGORY: '카테고리',
  RESTAURANT_PARKING: '주차 여부',
  RESTAURANT_ADDRESS: '주소',
  RESTAURANT_IMAGE: '레스토랑 이미지',
};

export const PLACEHOLDER = {
  ID: 'elice@gmail.com',
  PASSWORD: '최소 8자 이상의 비밀번호를 입력해 주세요',
  PASSWORD_CONFIRM: '',
  NAME: '2글자 이상의 이름을 입력해 주세요',
  NICKNAME: '닉네임',
  EMAIL: 'elice@gmail.com',
  PHONE: '01012345678',
  AMDIN_CODE: '',
  OWNER_REGISTRATION_NUMBER: '000-00-00000',
  RESTAURANT_NAME: '업체명',
  RESTAURANT_OFFICE: '강남역점',
  RESTAURANT_PHONE: '02-1234-5678',
  RESTAURANT_CATEGORY: '카테고리 선택',
  RESTAURANT_ADDRESS: '주소',
};

export const BUTTON = {
  USER_LOGIN: '로그인',
  USER_RESIGNTER: '회원가입',
  USER_SECURITY_MODIFY: '회원정보 수정',
  USER_MEMBER_DELETE: '회원정보 안전하게 삭제하기',
  SAVE_MODIFY_DATA: '변경사항 저장',
};
