export const SELECT_CATEGORY_OPTIONS = [
  { value: 'selectKorea', name: '한정식' },
  { value: 'selectMeat', name: '육류,고기요리' },
  { value: 'selectSeafood', name: '해물,생선요리' },
  { value: 'selectDining', name: '다이닝바' },
  { value: 'selectChicken', name: '닭,오리요리' },
  { value: 'selectBuffet', name: '뷔페' },
  { value: 'selectCourse', name: '코스요리' },
  { value: 'selectFamilyRestaurant', name: '패밀리레스토랑' },
  { value: 'selectCafe', name: '카페,디저트' },
  { value: 'selectVegan', name: '베지테리안/비건' },
  { value: 'selectBrunch', name: '브런치' },
  { value: 'selectNoodle', name: '국수,냉면' },
  { value: 'selectPizza', name: '피자' },
  { value: 'selectPasta', name: '파스타' },
];

export const SELECT_TIME = [
  { value: '10', name: '10' },
  { value: '20', name: '20' },
];

export const LABELTITLE = {
  ID: '아이디',
  PASSWORD: '비밀번호',
  PASSWORD_CONFIRM: '비밀번호 확인',
  PASSWORD_CURRENT: '현재 비밀번호',
  NAME: '이름',
  NICKNAME: '닉네임',
  EMAIL: '이메일',
  PHONE: '전화번호',
  ROLE_OWNER: '사장님이신가요?',
  ROLE_OWNER_SUB_TITLE: '사업관리자 계정으로 회원가입하기',
  ROLE_ADMIN: '관리자로 가입하기',
  AMDIN_CODE: 'ADMIN CODE',
  ADDRESS: '주소',
  ADDRESS_POSTNUMBER: '우편 번호',
  ADDRESS_ADDRESS1: '기본 주소',
  ADDRESS_ADDRESS2: '나머지 주소',
  OWNER_REGISTRATION_NUMBER: '사업자 등록번호',
  RESTAURANT_NAME: '업체명',
  RESTAURANT_OFFICE: '지점',
  RESTAURANT_PHONE: '대표번호',
  RESTAURANT_CATEGORY: '카테고리',
  RESTAURANT_PARKING: '주차 여부',
  RESTAURANT_IMAGE: '레스토랑 이미지',
  DESCRIPTION: '설명',
  MENU_NAME: '메뉴명',
  PRICE: '가격',
  OPEN_TIME: '오픈시간',
  CLOSE_TIME: '마지막 주문 시간',
  RESERVES_DATE: '예약 가능 날짜',
};

export const PLACEHOLDER = {
  ID: 'elice@gmail.com',
  PASSWORD: '최소 8자 이상의 비밀번호를 입력해 주세요',
  PASSWORD_CONFIRM: '',
  PASSWORD_CURRENT: '현재 비밀번호를 입력해주세요.',
  NAME: '2글자 이상의 이름을 입력해 주세요',
  NICKNAME: '닉네임',
  EMAIL: 'elice@gmail.com',
  PHONE: '01012345678',
  AMDIN_CODE: '',
  ADDRESS: '주소',
  ADDRESS_POSTNUMBER: '우편 번호',
  ADDRESS_ADDRESS1: '기본 주소',
  ADDRESS_ADDRESS2: '나머지 주소',
  OWNER_REGISTRATION_NUMBER: '000-00-00000',
  RESTAURANT_NAME: '업체명',
  RESTAURANT_OFFICE: '강남역점',
  RESTAURANT_PHONE: '02-1234-5678',
  RESTAURANT_CATEGORY: '카테고리 선택',
};

export const BUTTON = {
  USER_LOGIN: '로그인',
  USER_RESIGNTER: '회원가입',
  USER_SECURITY_MODIFY: '회원정보 수정',
  USER_MEMBER_DELETE: '회원정보 안전하게 삭제하기',
  SAVE_MODIFY_DATA: '변경사항 저장',
  REGISTER: '등록하기',
};
