export const URL = {
  HOME: '/',
  RESTAURANT: '/restaurant',
  SEARCH: '/search',
  USERS_LOGIN: '/users/login',
  USERS_REGISTER: '/users/register',
  USERS_SECURITY: '/users/security',
  USERS_SIGNOUT: '/users/signout',
  ACCOUNT_RESTAURANTS_HOME: '/account/myrestaurants',
  ACCOUNT_RESTAURANTS: '/account/restaurants',
  ACCOUNT_RESERVES: '/account/reserves',
  ACCOUNT_LIKES: '/account/likes',
  ACCOUNT_USERS: '/account/users',
  ACCOUNT_MENUS: '/account/menus',
  ACCOUNT_CATEGORIES: '/account/categories',
  PAGE_404: '/404',
  PAGE_401: '/401',
};
